plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
paginate: 10
paginate_path: "/page:num/"

# Site settings
title: amihaiemil.com | Programming blog
email: amihaiemil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about programming. Posts will cover various topics,
  and open source projects.
url: http://www.amihaiemil.com # the base hostname & protocol for your site
twitter_username: amihaiemil
github_username:  amihaiemil

include: ['.well-known']

# Build settings
timezone: Romania/Bucharest
markdown: kramdown

lsi: false
safe: true
whitelist:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
